// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "confluence_fake/internal/logic/device"
	_ "confluence_fake/internal/logic/fakers"
	_ "confluence_fake/internal/logic/validator"
)
