// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type IValidatorI interface {
	Ok()
}

var localValidatorI IValidatorI

func ValidatorI() IValidatorI {
	if localValidatorI == nil {
		panic("implement not found for interface IValidatorI, forgot register?")
	}
	return localValidatorI
}

func RegisterValidatorI(i IValidatorI) {
	localValidatorI = i
}
